CREATE DATABASE IF NOT EXISTS usuarios_api;
USE usuarios_api;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50),
  email VARCHAR(100),
  estado TINYINT
);
